# This workflow will install dependencies and run tests

name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - name: Install dependencies
      run: |
        npm i --include=dev
    - name: Run tests
      run: |
        npm run test
